name: Bhashit Parikh's blog
description: Bhashit Parikh's blog. Programming, Learning, Books and Ranting.
url: http://bhashit.github.io
markdown: redcarpet
pygments: true

gems:
- jemoji


redcarpet:
  extensions: [smart]
