name: Bhashit Parikh's blog
description: Bhashit Parikh's blog. Programming, Learning, Books and Ranting.
url: http://bhashitparikh.com

markdown:  kramdown
highlighter: rouge

gems:
- jemoji

kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false

